const char mapInfo[] = 
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
"a       #                                                                                                                      a"
"a       #                                                                                                                      a"
"a       #                                                                                                                      a"
"b       #                                                                                                                      a"
"b       #            aaaaaaa                                                                                                   a"
"b       #                                                                                                                      a"
"a       #                                                                                                                      a"
"a       #                                                                                                                      a"
"a       #             aaaaaa                                                                                                   a"
"a   aaaaa a                                                                                                                    a"
"a                                                                                                                              a"
"a                                                                                                                              a"
"a              aaaaa a                                                                                                         a"
"a                                                                                                                              a"
"a     aaaaa           a a aa  aaa        aaaa                                                                                  a"
"a                                a   a       a                                                                                 a"
"a            aaaaaa                aaa       a                                                                                 a"
"a                               a                                                                                              a"
"a                        a  a             a a                                                                                  a"
"a    aaaaa                a    a          a                                                                                    a"
"a                                        aa      aaaa                                                                          a"
"a                                 aaaa                                                                                         a"
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
